// AUTO-GENERATED from /workspace/_app-specs/homeowners-application/fields.json
// (extracted from the fillable AcroForm of Homeowners_Insurance_Application.pdf).
// 281 fields — 188 text, 93 checkbox — in original PDF order.
// Yes/No question text from yesno-questions.json (recovered positionally from the
// same PDF via widget coordinates). Display text only — no field name changes.
// DO NOT hand-edit: field names, labels, order and types are authoritative.

export type HoaField = {
  name: string;
  type: "text" | "checkbox";
  label: string;
  maxlen: number | null;
};

export type HoaSection = {
  page: number;
  heading: string;
  fields: HoaField[];
};

export const HOA_SECTIONS: HoaSection[] = [
  {
    page: 1,
    heading: "1. Applicant and Policy Information",
    fields: [
      { name: "primary_applicant_-_full_legal_name_1", type: "text", label: "Primary Applicant - Full Legal Name", maxlen: 100 },
      { name: "date_of_birth_2", type: "text", label: "Date of Birth", maxlen: 100 },
      { name: "marital_status_3", type: "text", label: "Marital Status", maxlen: 100 },
      { name: "co-applicant_-_full_legal_name_4", type: "text", label: "Co-Applicant - Full Legal Name", maxlen: 100 },
      { name: "date_of_birth_5", type: "text", label: "Date of Birth", maxlen: 100 },
      { name: "marital_status_6", type: "text", label: "Marital Status", maxlen: 100 },
      { name: "primary_phone_7", type: "text", label: "Primary Phone", maxlen: 100 },
      { name: "alternate_phone_8", type: "text", label: "Alternate Phone", maxlen: 100 },
      { name: "email_address_9", type: "text", label: "Email Address", maxlen: 100 },
      { name: "current_mailing_address_10", type: "text", label: "Current Mailing Address", maxlen: 100 },
      { name: "city_11", type: "text", label: "City", maxlen: 100 },
      { name: "state_12", type: "text", label: "State", maxlen: 100 },
      { name: "zip_13", type: "text", label: "ZIP", maxlen: 100 },
      { name: "applicant_occupation_14", type: "text", label: "Applicant Occupation", maxlen: 100 },
      { name: "employer_15", type: "text", label: "Employer", maxlen: 100 },
      { name: "years_employed_16", type: "text", label: "Years Employed", maxlen: 100 },
      { name: "co-applicant_occupation_17", type: "text", label: "Co-Applicant Occupation", maxlen: 100 },
      { name: "employer_18", type: "text", label: "Employer", maxlen: 100 },
      { name: "years_employed_19", type: "text", label: "Years Employed", maxlen: 100 },
      { name: "applicant_driver_license_number_20", type: "text", label: "Applicant Driver License Number", maxlen: 100 },
      { name: "state_21", type: "text", label: "State", maxlen: 100 },
      { name: "co-applicant_driver_license_number_22", type: "text", label: "Co-Applicant Driver License Number", maxlen: 100 },
      { name: "state_23", type: "text", label: "State", maxlen: 100 },
      { name: "requested_effective_date_24", type: "text", label: "Requested Effective Date", maxlen: 100 },
      { name: "current_carrier_25", type: "text", label: "Current Carrier", maxlen: 100 },
      { name: "current_policy_number_26", type: "text", label: "Current Policy Number", maxlen: 100 },
      { name: "current_annual_premium_27", type: "text", label: "Current Annual Premium", maxlen: 100 },
      { name: "years_with_current_carrier_28", type: "text", label: "Years With Current Carrier", maxlen: 100 },
      { name: "expiration_date_29", type: "text", label: "Expiration Date", maxlen: 100 },
      { name: "reason_for_shopping_30", type: "text", label: "Reason for Shopping", maxlen: 100 },
      { name: "email_documents_31", type: "checkbox", label: "Email documents", maxlen: null },
      { name: "mail_documents_32", type: "checkbox", label: "Mail documents", maxlen: null },
      { name: "text_notifications_33", type: "checkbox", label: "Text notifications", maxlen: null },
      { name: "electronic_signature_34", type: "checkbox", label: "Electronic signature", maxlen: null },
      { name: "additional_named_insureds_or_household_contacts_35", type: "text", label: "Additional named insureds or household contacts", maxlen: 100 },
    ],
  },
  {
    page: 2,
    heading: "2. Property, Occupancy, and Ownership",
    fields: [
      { name: "property_street_address_36", type: "text", label: "Property Street Address", maxlen: 100 },
      { name: "city_37", type: "text", label: "City", maxlen: 100 },
      { name: "state_38", type: "text", label: "State", maxlen: 100 },
      { name: "zip_39", type: "text", label: "ZIP", maxlen: 100 },
      { name: "county_40", type: "text", label: "County", maxlen: 100 },
      { name: "purchase_date_41", type: "text", label: "Purchase Date", maxlen: 100 },
      { name: "purchase_price_42", type: "text", label: "Purchase Price", maxlen: 100 },
      { name: "estimated_market_value_43", type: "text", label: "Estimated Market Value", maxlen: 100 },
      { name: "named_owner(s)_on_deed_44", type: "text", label: "Named Owner(s) on Deed", maxlen: 100 },
      { name: "entity___trust_name,_if_any_45", type: "text", label: "Entity / Trust Name, if any", maxlen: 100 },
      { name: "primary_residence_46", type: "checkbox", label: "Primary residence", maxlen: null },
      { name: "secondary_residence_47", type: "checkbox", label: "Secondary residence", maxlen: null },
      { name: "seasonal_residence_48", type: "checkbox", label: "Seasonal residence", maxlen: null },
      { name: "tenant_occupied_49", type: "checkbox", label: "Tenant occupied", maxlen: null },
      { name: "vacant_50", type: "checkbox", label: "Vacant", maxlen: null },
      { name: "under_renovation_51", type: "checkbox", label: "Under renovation", maxlen: null },
      { name: "new_purchase_52", type: "checkbox", label: "New purchase", maxlen: null },
      { name: "existing_residence_53", type: "checkbox", label: "Existing residence", maxlen: null },
      { name: "short-term_rental_54", type: "checkbox", label: "Short-term rental", maxlen: null },
      { name: "date_occupied___expected_occupancy_55", type: "text", label: "Date Occupied / Expected Occupancy", maxlen: 100 },
      { name: "number_of_families_56", type: "text", label: "Number of Families", maxlen: 100 },
      { name: "number_of_residents_57", type: "text", label: "Number of Residents", maxlen: 100 },
      { name: "months_occupied_per_year_58", type: "text", label: "Months Occupied Per Year", maxlen: 100 },
      { name: "adults_in_household_59", type: "text", label: "Adults in Household", maxlen: 100 },
      { name: "children_in_household_60", type: "text", label: "Children in Household", maxlen: 100 },
      { name: "unrelated_residents_61", type: "text", label: "Unrelated Residents", maxlen: 100 },
      { name: "domestic_employees_62", type: "text", label: "Domestic Employees", maxlen: 100 },
      { name: "yes_63", type: "checkbox", label: "Yes", maxlen: null },
      { name: "no_64", type: "checkbox", label: "No", maxlen: null },
      { name: "yes_65", type: "checkbox", label: "Yes", maxlen: null },
      { name: "no_66", type: "checkbox", label: "No", maxlen: null },
      { name: "yes_67", type: "checkbox", label: "Yes", maxlen: null },
      { name: "no_68", type: "checkbox", label: "No", maxlen: null },
      { name: "yes_69", type: "checkbox", label: "Yes", maxlen: null },
      { name: "no_70", type: "checkbox", label: "No", maxlen: null },
      { name: "describe_any_business,_rental,_or_unusual_occupancy_exposure_71", type: "text", label: "Describe any business, rental, or unusual occupancy exposure", maxlen: 100 },
      { name: "prior_address_72", type: "text", label: "Prior Address", maxlen: 100 },
      { name: "city_73", type: "text", label: "City", maxlen: 100 },
      { name: "state_74", type: "text", label: "State", maxlen: 100 },
      { name: "zip_75", type: "text", label: "ZIP", maxlen: 100 },
      { name: "years_at_prior_address_76", type: "text", label: "Years at Prior Address", maxlen: 100 },
      { name: "prior_residence_type_77", type: "text", label: "Prior Residence Type", maxlen: 100 },
      { name: "prior_insurance_carrier_78", type: "text", label: "Prior Insurance Carrier", maxlen: 100 },
    ],
  },
  {
    page: 3,
    heading: "3. Dwelling Construction and Building Details",
    fields: [
      { name: "year_built_79", type: "text", label: "Year Built", maxlen: 100 },
      { name: "total_living_area_sq._ft._80", type: "text", label: "Total Living Area Sq. Ft.", maxlen: 100 },
      { name: "number_of_stories_81", type: "text", label: "Number of Stories", maxlen: 100 },
      { name: "number_of_units_82", type: "text", label: "Number of Units", maxlen: 100 },
      { name: "construction_type_83", type: "text", label: "Construction Type", maxlen: 100 },
      { name: "exterior_wall_material_84", type: "text", label: "Exterior Wall Material", maxlen: 100 },
      { name: "foundation_type_85", type: "text", label: "Foundation Type", maxlen: 100 },
      { name: "roof_shape_86", type: "text", label: "Roof Shape", maxlen: 100 },
      { name: "roof_material_87", type: "text", label: "Roof Material", maxlen: 100 },
      { name: "roof_year___age_88", type: "text", label: "Roof Year / Age", maxlen: 100 },
      { name: "roof_condition_89", type: "text", label: "Roof Condition", maxlen: 100 },
      { name: "roof_replacement_cost_90", type: "text", label: "Roof Replacement Cost", maxlen: 100 },
      { name: "roof_permit_date_91", type: "text", label: "Roof Permit Date", maxlen: 100 },
      { name: "bedrooms_92", type: "text", label: "Bedrooms", maxlen: 100 },
      { name: "bathrooms_93", type: "text", label: "Bathrooms", maxlen: 100 },
      { name: "garage_spaces_94", type: "text", label: "Garage Spaces", maxlen: 100 },
      { name: "garage_type_95", type: "text", label: "Garage Type", maxlen: 100 },
      { name: "basement_sq._ft._96", type: "text", label: "Basement Sq. Ft.", maxlen: 100 },
      { name: "finished_basement_sq._ft._97", type: "text", label: "Finished Basement Sq. Ft.", maxlen: 100 },
      { name: "porch___deck_sq._ft._98", type: "text", label: "Porch / Deck Sq. Ft.", maxlen: 100 },
      { name: "carport_sq._ft._99", type: "text", label: "Carport Sq. Ft.", maxlen: 100 },
      { name: "other_attached_area_100", type: "text", label: "Other Attached Area", maxlen: 100 },
      { name: "flooring_type(s)_101", type: "text", label: "Flooring Type(s)", maxlen: 100 },
      { name: "kitchen_quality_102", type: "text", label: "Kitchen Quality", maxlen: 100 },
      { name: "bathroom_quality_103", type: "text", label: "Bathroom Quality", maxlen: 100 },
      { name: "custom_features_104", type: "text", label: "Custom Features", maxlen: 100 },
      { name: "detached_garage___shop_sq._ft._105", type: "text", label: "Detached Garage / Shop Sq. Ft.", maxlen: 100 },
      { name: "guest_house_sq._ft._106", type: "text", label: "Guest House Sq. Ft.", maxlen: 100 },
      { name: "other_structure_type_107", type: "text", label: "Other Structure Type", maxlen: 100 },
      { name: "fence_type___length_108", type: "text", label: "Fence Type / Length", maxlen: 100 },
      { name: "solar_panels_-_owned_or_leased_109", type: "text", label: "Solar Panels - Owned or Leased", maxlen: 100 },
      { name: "other_structure_value_110", type: "text", label: "Other Structure Value", maxlen: 100 },
      { name: "historic_home_111", type: "checkbox", label: "Historic home", maxlen: null },
      { name: "log_home_112", type: "checkbox", label: "Log home", maxlen: null },
      { name: "manufactured_home_113", type: "checkbox", label: "Manufactured home", maxlen: null },
      { name: "modular_home_114", type: "checkbox", label: "Modular home", maxlen: null },
      { name: "earth-sheltered_115", type: "checkbox", label: "Earth-sheltered", maxlen: null },
      { name: "eifs_/_synthetic_stucco_116", type: "checkbox", label: "EIFS / synthetic stucco", maxlen: null },
      { name: "flat_roof_117", type: "checkbox", label: "Flat roof", maxlen: null },
      { name: "wood_shake_roof_118", type: "checkbox", label: "Wood shake roof", maxlen: null },
      { name: "unreinforced_masonry_119", type: "checkbox", label: "Unreinforced masonry", maxlen: null },
      { name: "describe_additions,_renovations,_custom_construction,_or_detached_structures_120", type: "text", label: "Describe additions, renovations, custom construction, or detached structures", maxlen: 100 },
    ],
  },
  {
    page: 4,
    heading: "4. Utilities, Systems, Protection, and Updates",
    fields: [
      { name: "electrical_service_amps_121", type: "text", label: "Electrical Service Amps", maxlen: 100 },
      { name: "wiring_type_122", type: "text", label: "Wiring Type", maxlen: 100 },
      { name: "electrical_update_year_123", type: "text", label: "Electrical Update Year", maxlen: 100 },
      { name: "generator_type___size_124", type: "text", label: "Generator Type / Size", maxlen: 100 },
      { name: "plumbing_type_125", type: "text", label: "Plumbing Type", maxlen: 100 },
      { name: "plumbing_update_year_126", type: "text", label: "Plumbing Update Year", maxlen: 100 },
      { name: "water_heater_type___age_127", type: "text", label: "Water Heater Type / Age", maxlen: 100 },
      { name: "sewer___septic_128", type: "text", label: "Sewer / Septic", maxlen: 100 },
      { name: "primary_heat_type_129", type: "text", label: "Primary Heat Type", maxlen: 100 },
      { name: "heating_update_year_130", type: "text", label: "Heating Update Year", maxlen: 100 },
      { name: "central_ac_type___age_131", type: "text", label: "Central AC Type / Age", maxlen: 100 },
      { name: "secondary_heat_source_132", type: "text", label: "Secondary Heat Source", maxlen: 100 },
      { name: "public___private_water_133", type: "text", label: "Public / Private Water", maxlen: 100 },
      { name: "well_depth___age_134", type: "text", label: "Well Depth / Age", maxlen: 100 },
      { name: "public_sewer___septic_age_135", type: "text", label: "Public Sewer / Septic Age", maxlen: 100 },
      { name: "fuel_tank_location___size_136", type: "text", label: "Fuel Tank Location / Size", maxlen: 100 },
      { name: "gas_provider_137", type: "text", label: "Gas Provider", maxlen: 100 },
      { name: "propane_provider_138", type: "text", label: "Propane Provider", maxlen: 100 },
      { name: "oil_tank_age_139", type: "text", label: "Oil Tank Age", maxlen: 100 },
      { name: "water_shutoff_device_140", type: "text", label: "Water Shutoff Device", maxlen: 100 },
      { name: "central_station_burglar_alarm_141", type: "checkbox", label: "Central station burglar alarm", maxlen: null },
      { name: "central_station_fire_alarm_142", type: "checkbox", label: "Central station fire alarm", maxlen: null },
      { name: "local_alarm_only_143", type: "checkbox", label: "Local alarm only", maxlen: null },
      { name: "smoke_detectors_144", type: "checkbox", label: "Smoke detectors", maxlen: null },
      { name: "carbon_monoxide_detectors_145", type: "checkbox", label: "Carbon monoxide detectors", maxlen: null },
      { name: "fire_extinguishers_146", type: "checkbox", label: "Fire extinguishers", maxlen: null },
      { name: "sprinkler_system_147", type: "checkbox", label: "Sprinkler system", maxlen: null },
      { name: "deadbolt_locks_148", type: "checkbox", label: "Deadbolt locks", maxlen: null },
      { name: "gated_community_149", type: "checkbox", label: "Gated community", maxlen: null },
      { name: "security_cameras_150", type: "checkbox", label: "Security cameras", maxlen: null },
      { name: "leak_detection_151", type: "checkbox", label: "Leak detection", maxlen: null },
      { name: "distance_to_fire_hydrant_152", type: "text", label: "Distance to Fire Hydrant", maxlen: 100 },
      { name: "distance_to_fire_station_153", type: "text", label: "Distance to Fire Station", maxlen: 100 },
      { name: "fire_department_type_154", type: "text", label: "Fire Department Type", maxlen: 100 },
      { name: "yes_155", type: "checkbox", label: "Yes", maxlen: null },
      { name: "no_156", type: "checkbox", label: "No", maxlen: null },
      { name: "yes_157", type: "checkbox", label: "Yes", maxlen: null },
      { name: "no_158", type: "checkbox", label: "No", maxlen: null },
      { name: "yes_159", type: "checkbox", label: "Yes", maxlen: null },
      { name: "no_160", type: "checkbox", label: "No", maxlen: null },
      { name: "yes_161", type: "checkbox", label: "Yes", maxlen: null },
      { name: "no_162", type: "checkbox", label: "No", maxlen: null },
      { name: "explain_any_yes_answers_and_list_completed_updates_with_dates_163", type: "text", label: "Explain any yes answers and list completed updates with dates", maxlen: 100 },
    ],
  },
  {
    page: 5,
    heading: "5. Premises Liability and Underwriting Exposures",
    fields: [
      { name: "number_of_dogs_164", type: "text", label: "Number of Dogs", maxlen: 100 },
      { name: "breed(s)_165", type: "text", label: "Breed(s)", maxlen: 100 },
      { name: "number_of_other_animals_166", type: "text", label: "Number of Other Animals", maxlen: 100 },
      { name: "animal_type(s)_167", type: "text", label: "Animal Type(s)", maxlen: 100 },
      { name: "any_bite_or_attack_history?_168", type: "text", label: "Any Bite or Attack History?", maxlen: 100 },
      { name: "date___details_169", type: "text", label: "Date / Details", maxlen: 100 },
      { name: "livestock___farm_animals?_170", type: "text", label: "Livestock / Farm Animals?", maxlen: 100 },
      { name: "swimming_pool_171", type: "checkbox", label: "Swimming pool", maxlen: null },
      { name: "spa_/_hot_tub_172", type: "checkbox", label: "Spa / hot tub", maxlen: null },
      { name: "diving_board_173", type: "checkbox", label: "Diving board", maxlen: null },
      { name: "slide_174", type: "checkbox", label: "Slide", maxlen: null },
      { name: "pool_fenced_175", type: "checkbox", label: "Pool fenced", maxlen: null },
      { name: "trampoline_176", type: "checkbox", label: "Trampoline", maxlen: null },
      { name: "treehouse_177", type: "checkbox", label: "Treehouse", maxlen: null },
      { name: "play_structure_178", type: "checkbox", label: "Play structure", maxlen: null },
      { name: "zip_line_179", type: "checkbox", label: "Zip line", maxlen: null },
      { name: "skate_ramp_180", type: "checkbox", label: "Skate ramp", maxlen: null },
      { name: "pond_/_lake_181", type: "checkbox", label: "Pond / lake", maxlen: null },
      { name: "dock_182", type: "checkbox", label: "Dock", maxlen: null },
      { name: "boat_lift_183", type: "checkbox", label: "Boat lift", maxlen: null },
      { name: "atv_/_dirt_bike_use_184", type: "checkbox", label: "ATV / dirt bike use", maxlen: null },
      { name: "shooting_range_185", type: "checkbox", label: "Shooting range", maxlen: null },
      { name: "pool_type___year_186", type: "text", label: "Pool Type / Year", maxlen: 100 },
      { name: "fence_height___gate_type_187", type: "text", label: "Fence Height / Gate Type", maxlen: 100 },
      { name: "water_feature_details_188", type: "text", label: "Water Feature Details", maxlen: 100 },
      { name: "yes_189", type: "checkbox", label: "Yes", maxlen: null },
      { name: "no_190", type: "checkbox", label: "No", maxlen: null },
      { name: "yes_191", type: "checkbox", label: "Yes", maxlen: null },
      { name: "no_192", type: "checkbox", label: "No", maxlen: null },
      { name: "yes_193", type: "checkbox", label: "Yes", maxlen: null },
      { name: "no_194", type: "checkbox", label: "No", maxlen: null },
      { name: "yes_195", type: "checkbox", label: "Yes", maxlen: null },
      { name: "no_196", type: "checkbox", label: "No", maxlen: null },
      { name: "yes_197", type: "checkbox", label: "Yes", maxlen: null },
      { name: "no_198", type: "checkbox", label: "No", maxlen: null },
      { name: "explain_any_yes_answers,_including_safeguards_and_dates_199", type: "text", label: "Explain any yes answers, including safeguards and dates", maxlen: 100 },
      { name: "number_of_vehicles_garaged_200", type: "text", label: "Number of Vehicles Garaged", maxlen: 100 },
      { name: "rv___boat_stored_on_site_201", type: "text", label: "RV / Boat Stored On Site", maxlen: 100 },
      { name: "commercial_vehicle_use_202", type: "text", label: "Commercial Vehicle Use", maxlen: 100 },
    ],
  },
  {
    page: 6,
    heading: "6. Coverage Selection and Valuation",
    fields: [
      { name: "coverage_a_-_dwelling_203", type: "text", label: "Coverage A - Dwelling", maxlen: 100 },
      { name: "coverage_b_-_other_structures_204", type: "text", label: "Coverage B - Other Structures", maxlen: 100 },
      { name: "coverage_c_-_personal_property_205", type: "text", label: "Coverage C - Personal Property", maxlen: 100 },
      { name: "coverage_d_-_loss_of_use_206", type: "text", label: "Coverage D - Loss of Use", maxlen: 100 },
      { name: "coverage_e_-_personal_liability_207", type: "text", label: "Coverage E - Personal Liability", maxlen: 100 },
      { name: "coverage_f_-_medical_payments_208", type: "text", label: "Coverage F - Medical Payments", maxlen: 100 },
      { name: "all_other_perils_deductible_209", type: "text", label: "All Other Perils Deductible", maxlen: 100 },
      { name: "wind___hail_deductible_210", type: "text", label: "Wind / Hail Deductible", maxlen: 100 },
      { name: "named_storm_deductible_211", type: "text", label: "Named Storm Deductible", maxlen: 100 },
      { name: "replacement_cost_on_contents_212", type: "checkbox", label: "Replacement cost on contents", maxlen: null },
      { name: "extended_dwelling_replacement_213", type: "checkbox", label: "Extended dwelling replacement", maxlen: null },
      { name: "guaranteed_replacement_cost_214", type: "checkbox", label: "Guaranteed replacement cost", maxlen: null },
      { name: "water_backup_215", type: "checkbox", label: "Water backup", maxlen: null },
      { name: "service_line_216", type: "checkbox", label: "Service line", maxlen: null },
      { name: "equipment_breakdown_217", type: "checkbox", label: "Equipment breakdown", maxlen: null },
      { name: "ordinance_or_law_218", type: "checkbox", label: "Ordinance or law", maxlen: null },
      { name: "identity_theft_219", type: "checkbox", label: "Identity theft", maxlen: null },
      { name: "home_systems_220", type: "checkbox", label: "Home systems", maxlen: null },
      { name: "scheduled_property_221", type: "checkbox", label: "Scheduled property", maxlen: null },
      { name: "home_cyber_222", type: "checkbox", label: "Home cyber", maxlen: null },
      { name: "earthquake_223", type: "checkbox", label: "Earthquake", maxlen: null },
      { name: "flood_quote_requested_224", type: "checkbox", label: "Flood quote requested", maxlen: null },
      { name: "personal_injury_225", type: "checkbox", label: "Personal injury", maxlen: null },
      { name: "umbrella_quote_226", type: "checkbox", label: "Umbrella quote", maxlen: null },
      { name: "jewelry_estimated_value_227", type: "text", label: "Jewelry Estimated Value", maxlen: 100 },
      { name: "fine_arts_value_228", type: "text", label: "Fine Arts Value", maxlen: 100 },
      { name: "firearms_value_229", type: "text", label: "Firearms Value", maxlen: 100 },
      { name: "collectibles_value_230", type: "text", label: "Collectibles Value", maxlen: 100 },
      { name: "musical_instruments_value_231", type: "text", label: "Musical Instruments Value", maxlen: 100 },
      { name: "other_scheduled_property_232", type: "text", label: "Other Scheduled Property", maxlen: 100 },
      { name: "list_high-value_items,_appraisals,_and_requested_scheduled_limits_233", type: "text", label: "List high-value items, appraisals, and requested scheduled limits", maxlen: 100 },
      { name: "estimated_dwelling_replacement_cost_234", type: "text", label: "Estimated Dwelling Replacement Cost", maxlen: 100 },
      { name: "source___estimator_235", type: "text", label: "Source / Estimator", maxlen: 100 },
      { name: "estimate_date_236", type: "text", label: "Estimate Date", maxlen: 100 },
      { name: "estimated_personal_property_value_237", type: "text", label: "Estimated Personal Property Value", maxlen: 100 },
      { name: "estimated_additional_living_expense_need_238", type: "text", label: "Estimated Additional Living Expense Need", maxlen: 100 },
    ],
  },
  {
    page: 7,
    heading: "7. Loss History, Mortgagee, Remarks, and Authorization",
    fields: [
      { name: "loss_0_Date_239", type: "text", label: "Date", maxlen: 100 },
      { name: "loss_0_Location_240", type: "text", label: "Location", maxlen: 100 },
      { name: "loss_0_Type / Cause_241", type: "text", label: "Type / Cause", maxlen: 100 },
      { name: "loss_0_Amount Paid_242", type: "text", label: "Amount Paid", maxlen: 100 },
      { name: "loss_0_Status_243", type: "text", label: "Status", maxlen: 100 },
      { name: "loss_0_Claim Number_244", type: "text", label: "Claim Number", maxlen: 100 },
      { name: "loss_1_Date_245", type: "text", label: "Date", maxlen: 100 },
      { name: "loss_1_Location_246", type: "text", label: "Location", maxlen: 100 },
      { name: "loss_1_Type / Cause_247", type: "text", label: "Type / Cause", maxlen: 100 },
      { name: "loss_1_Amount Paid_248", type: "text", label: "Amount Paid", maxlen: 100 },
      { name: "loss_1_Status_249", type: "text", label: "Status", maxlen: 100 },
      { name: "loss_1_Claim Number_250", type: "text", label: "Claim Number", maxlen: 100 },
      { name: "loss_2_Date_251", type: "text", label: "Date", maxlen: 100 },
      { name: "loss_2_Location_252", type: "text", label: "Location", maxlen: 100 },
      { name: "loss_2_Type / Cause_253", type: "text", label: "Type / Cause", maxlen: 100 },
      { name: "loss_2_Amount Paid_254", type: "text", label: "Amount Paid", maxlen: 100 },
      { name: "loss_2_Status_255", type: "text", label: "Status", maxlen: 100 },
      { name: "loss_2_Claim Number_256", type: "text", label: "Claim Number", maxlen: 100 },
      { name: "loss_3_Date_257", type: "text", label: "Date", maxlen: 100 },
      { name: "loss_3_Location_258", type: "text", label: "Location", maxlen: 100 },
      { name: "loss_3_Type / Cause_259", type: "text", label: "Type / Cause", maxlen: 100 },
      { name: "loss_3_Amount Paid_260", type: "text", label: "Amount Paid", maxlen: 100 },
      { name: "loss_3_Status_261", type: "text", label: "Status", maxlen: 100 },
      { name: "loss_3_Claim Number_262", type: "text", label: "Claim Number", maxlen: 100 },
      { name: "mortgage_company___lender_263", type: "text", label: "Mortgage Company / Lender", maxlen: 100 },
      { name: "loan_number_264", type: "text", label: "Loan Number", maxlen: 100 },
      { name: "mortgagee_mailing_address_265", type: "text", label: "Mortgagee Mailing Address", maxlen: 100 },
      { name: "city_266", type: "text", label: "City", maxlen: 100 },
      { name: "state_267", type: "text", label: "State", maxlen: 100 },
      { name: "zip_268", type: "text", label: "ZIP", maxlen: 100 },
      { name: "second_mortgage___heloc_lender_269", type: "text", label: "Second Mortgage / HELOC Lender", maxlen: 100 },
      { name: "loan_number_270", type: "text", label: "Loan Number", maxlen: 100 },
      { name: "additional_underwriting_remarks_271", type: "text", label: "Additional underwriting remarks", maxlen: 100 },
      { name: "prior_declarations_attached_272", type: "checkbox", label: "Prior declarations attached", maxlen: null },
      { name: "loss_runs_attached_273", type: "checkbox", label: "Loss runs attached", maxlen: null },
      { name: "inspection_attached_274", type: "checkbox", label: "Inspection attached", maxlen: null },
      { name: "photos_attached_275", type: "checkbox", label: "Photos attached", maxlen: null },
      { name: "applicant_signature_276", type: "text", label: "Applicant Signature", maxlen: 100 },
      { name: "date_277", type: "text", label: "Date", maxlen: 100 },
      { name: "producer___agency_278", type: "text", label: "Producer / Agency", maxlen: 100 },
      { name: "co-applicant_signature_279", type: "text", label: "Co-Applicant Signature", maxlen: 100 },
      { name: "date_280", type: "text", label: "Date", maxlen: 100 },
      { name: "producer_phone_281", type: "text", label: "Producer Phone", maxlen: 100 },
    ],
  },
];

/** Question text for each Yes/No pair, keyed by the pair's "Yes" field name. */
export const HOA_YESNO_QUESTIONS: Record<string, string> = {
  "yes_63": "Home-based business conducted on premises?",
  "yes_65": "Any customers or employees visit the premises?",
  "yes_67": "Any room, unit, or structure rented to others?",
  "yes_69": "Any short-term rental activity (Airbnb/VRBO)?",
  "yes_155": "Any knob-and-tube, aluminum, or cloth wiring?",
  "yes_157": "Any polybutylene, galvanized, or lead plumbing?",
  "yes_159": "Any active leaks, unrepaired damage, or maintenance issues?",
  "yes_161": "Any open permits or code violations?",
  "yes_189": "Any firearms kept on premises?",
  "yes_191": "Any wood stove, fireplace, or solid-fuel appliance?",
  "yes_193": "Any unusually steep terrain, retaining wall, or cliff exposure?",
  "yes_195": "Any prior foreclosure, bankruptcy, or insurance cancellation?",
  "yes_197": "Any resident with a felony conviction or fraud-related offense?",
};

export const HOA_FIELD_COUNT = HOA_SECTIONS.reduce((n, s) => n + s.fields.length, 0);
